import { readFileSync, writeFileSync } from 'node:fs';

const replacements = [
  ['Geld-zurueck', 'Geld-zurück'],
  ['Verstaendnis', 'Verständnis'],
  ['Selbstverstaendlich', 'Selbstverständlich'],
  ['vorlaeufig', 'vorläufig'],
  ['naturgemaess', 'naturgemäß'],
  ['regelmaessig', 'regelmäßig'],
  ['gegenueber', 'gegenüber'],
  ['hierueber', 'hierüber'],
  ['darueber', 'darüber'],
  ['Darueber', 'Darüber'],
  ['worueber', 'worüber'],
  ['ueberzeug', 'überzeug'],
  ['Ueberzeug', 'Überzeug'],
  ['ueberhaupt', 'überhaupt'],
  ['Ueberhaupt', 'Überhaupt'],
  ['ueberraschend', 'überraschend'],
  ['Ueberraschung', 'Überraschung'],
  ['uebersehen', 'übersehen'],
  ['uebersieht', 'übersieht'],
  ['Uebersicht', 'Übersicht'],
  ['uebertreib', 'übertreib'],
  ['uebernehm', 'übernehm'],
  ['Uebernehm', 'Übernehm'],
  ['ueberlegen', 'überlegen'],
  ['ueberleg', 'überleg'],
  ['ueberprueft', 'überprüft'],
  ['ueberprüf', 'überprüf'],
  ['Ueberblick', 'Überblick'],
  ['ueberblick', 'überblick'],
  ['Ueberweisung', 'Überweisung'],
  ['ueberweisen', 'überweisen'],

  ['muessen', 'müssen'],
  ['Muessen', 'Müssen'],
  ['muesst', 'müsst'],
  ['koennen', 'können'],
  ['Koennen', 'Können'],
  ['koennt', 'könnt'],
  ['koennte', 'könnte'],
  ['Koennte', 'Könnte'],
  ['fuehl', 'fühl'],
  ['Fuehl', 'Fühl'],
  ['fuer ', 'für '],
  ['fuer.', 'für.'],
  ['fuer,', 'für,'],
  ['fuer?', 'für?'],
  ['fuer!', 'für!'],
  ['fuer)', 'für)'],
  ['fuer:', 'für:'],
  ['fuer"', 'für"'],
  ['Fuer ', 'Für '],
  ['nuetz', 'nütz'],
  ['gluecklich', 'glücklich'],
  ['Glueck', 'Glück'],
  ['ueblich', 'üblich'],
  ['Ueblich', 'Üblich'],
  ['unueblich', 'unüblich'],
  ['Buero', 'Büro'],
  ['Bueros', 'Büros'],
  ['Tuer', 'Tür'],
  ['gruen', 'grün'],
  ['Gruen', 'Grün'],
  ['fuenf', 'fünf'],
  ['Fuenf', 'Fünf'],
  ['fuehrt', 'führt'],
  ['Fuehrt', 'Führt'],
  ['fuehrung', 'führung'],
  ['Fuehrung', 'Führung'],
  ['gefuehrt', 'geführt'],
  ['gefuehl', 'gefühl'],
  ['Gefuehl', 'Gefühl'],
  ['bemueh', 'bemüh'],
  ['gemueht', 'gemüht'],
  ['kuendig', 'kündig'],
  ['Kuendig', 'Kündig'],
  ['Schluess', 'Schlüss'],
  ['schluess', 'schlüss'],
  ['pruefen', 'prüfen'],
  ['Pruef', 'Prüf'],
  ['pruef', 'prüf'],
  ['frueh', 'früh'],
  ['Frueh', 'Früh'],
  ['frueher', 'früher'],
  ['wuerden', 'würden'],
  ['Wuerden', 'Würden'],
  ['wuerde', 'würde'],
  ['Wuerde', 'Würde'],
  ['stuerzt', 'stürzt'],
  ['huebsch', 'hübsch'],
  ['kuerz', 'kürz'],
  ['Kuerz', 'Kürz'],
  ['truebe', 'trübe'],
  ['Truebe', 'Trübe'],
  ['ruest', 'rüst'],
  ['Ruest', 'Rüst'],
  ['Stueck', 'Stück'],
  ['stueck', 'stück'],
  ['Brueck', 'Brück'],
  ['brueck', 'brück'],
  ['Bluet', 'Blüt'],
  ['Knuepf', 'Knüpf'],
  ['knuepf', 'knüpf'],
  ['Fuelle', 'Fülle'],
  ['fuelle', 'fülle'],
  ['fuell', 'füll'],
  ['saess', 'säß'],
  ['Saess', 'Säß'],
  ['fuegt', 'fügt'],
  ['einfueg', 'einfüg'],

  ['naechst', 'nächst'],
  ['Naechst', 'Nächst'],
  ['naeher', 'näher'],
  ['Naeher', 'Näher'],
  ['ungefaehr', 'ungefähr'],
  ['Maerkte', 'Märkte'],
  ['maerkte', 'märkte'],
  ['waehrend', 'während'],
  ['Waehrend', 'Während'],
  ['waehlt', 'wählt'],
  ['waehl', 'wähl'],
  ['Waehl', 'Wähl'],
  ['gewaehlt', 'gewählt'],
  ['erklaer', 'erklär'],
  ['Erklaer', 'Erklär'],
  ['erzaehl', 'erzähl'],
  ['Erzaehl', 'Erzähl'],
  ['zaehlt', 'zählt'],
  ['Zaehl', 'Zähl'],
  ['saemtlich', 'sämtlich'],
  ['Saetze', 'Sätze'],
  ['Saetz', 'Sätz'],
  ['saetze', 'sätze'],
  ['Plaetze', 'Plätze'],
  ['plaetze', 'plätze'],
  ['Plaetzen', 'Plätzen'],
  ['Plaetz', 'Plätz'],
  ['haett', 'hätt'],
  ['Haett', 'Hätt'],
  ['waer', 'wär'],
  ['Waer', 'Wär'],
  ['haengt', 'hängt'],
  ['Haengt', 'Hängt'],
  ['haeng', 'häng'],
  ['Haeng', 'Häng'],
  ['Anhaen', 'Anhän'],
  ['anhaen', 'anhän'],
  ['Empfaeng', 'Empfäng'],
  ['empfaeng', 'empfäng'],
  ['enttaeusch', 'enttäusch'],
  ['Enttaeusch', 'Enttäusch'],
  ['taeglich', 'täglich'],
  ['Taeglich', 'Täglich'],
  ['kaempf', 'kämpf'],
  ['Kaempf', 'Kämpf'],
  ['Raeum', 'Räum'],
  ['raeum', 'räum'],
  ['Laend', 'Länd'],
  ['laend', 'länd'],
  ['gefaehr', 'gefähr'],
  ['Gefaehr', 'Gefähr'],
  ['waechst', 'wächst'],
  ['gewaechst', 'gewächst'],
  ['Geschmaeck', 'Geschmäck'],
  ['Aerger', 'Ärger'],
  ['aerger', 'ärger'],
  ['Aenderung', 'Änderung'],
  ['aenderung', 'änderung'],
  ['aendern', 'ändern'],
  ['geaendert', 'geändert'],

  ['Koeln', 'Köln'],
  ['hoer', 'hör'],
  ['Hoer', 'Hör'],
  ['gehoert', 'gehört'],
  ['Gehoert', 'Gehört'],
  ['hoeher', 'höher'],
  ['Hoeher', 'Höher'],
  ['hoechst', 'höchst'],
  ['Hoechst', 'Höchst'],
  ['hoeflich', 'höflich'],
  ['Hoeflich', 'Höflich'],
  ['moegen', 'mögen'],
  ['moegl', 'mögl'],
  ['Moegl', 'Mögl'],
  ['moeglich', 'möglich'],
  ['unmoeglich', 'unmöglich'],
  ['stoer', 'stör'],
  ['Stoer', 'Stör'],
  ['groesste', 'größte'],
  ['Groesste', 'Größte'],
  ['groess', 'größ'],
  ['Groess', 'Größ'],
  ['noetig', 'nötig'],
  ['Noetig', 'Nötig'],
  ['schoen', 'schön'],
  ['Schoen', 'Schön'],
  ['Loesch', 'Lösch'],
  ['loesch', 'lösch'],
  ['Loesung', 'Lösung'],
  ['loesung', 'lösung'],
  ['Loes', 'Lös'],
  ['loes', 'lös'],
  ['boes', 'bös'],
  ['Boes', 'Bös'],
  ['Foerd', 'Förd'],
  ['foerd', 'förd'],
  ['oeffn', 'öffn'],
  ['Oeffn', 'Öffn'],
  ['oeffentlich', 'öffentlich'],
  ['Oeffentlich', 'Öffentlich'],
  ['Floet', 'Flöt'],
  ['Goet', 'Göt'],
  ['Bloed', 'Blöd'],
  ['bloed', 'blöd'],
  ['Roem', 'Röm'],
  ['Behoer', 'Behör'],
  ['behoer', 'behör'],

  ['Ueber ', 'Über '],
  ['Ueber-', 'Über-'],
  ['ueber ', 'über '],
  ['ueber-', 'über-'],
  ['ueber,', 'über,'],
  ['ueber.', 'über.'],
  ['Ueber.', 'Über.'],

  ['Duesseldorf', 'Düsseldorf'],
  ['Muenchen', 'München'],
  ['Nuernberg', 'Nürnberg'],
  ['Wuerzburg', 'Würzburg'],
  ['Saarbruecken', 'Saarbrücken'],

  ['Datenfluess', 'Datenflüss'],
  ['Schluessel', 'Schlüssel'],
  ['schluessel', 'schlüssel'],
  ['Ueberlebt', 'Überlebt'],
  ['ueberlebt', 'überlebt'],
  ['Ueberzeugt', 'Überzeugt'],
  ['Verlaeng', 'Verläng'],
  ['verlaeng', 'verläng'],
  ['Verfaelsch', 'Verfälsch'],
  ['Auftraege', 'Aufträge'],
  ['Vertraege', 'Verträge'],
  ['Anfraege', 'Anfräge'],
  ['Vorschlaege', 'Vorschläge'],
  ['Maerz', 'März'],
  ['naemlich', 'nämlich'],
  ['Naemlich', 'Nämlich'],
  ['laeuft', 'läuft'],
  ['Laeuft', 'Läuft'],
  ['laeufst', 'läufst'],
  ['Laeufst', 'Läufst'],
  ['laeut', 'läut'],
  ['Laeut', 'Läut'],
  ['laesst', 'lässt'],
  ['Laesst', 'Lässt'],
  ['fragt"', 'fragt"'], // unchanged
  ['paedag', 'pädag'],
  ['Paedag', 'Pädag'],
  ['ausuebt', 'ausübt'],
  ['ausueb', 'ausüb'],
  ['Ausueb', 'Ausüb'],
  ['Buegel', 'Bügel'],
  ['buegel', 'bügel'],
  ['ueblich', 'üblich'],
  ['ausserdem', 'außerdem'],
  ['draussen', 'draußen'],
  ['Strasse', 'Straße'],
  ['strasse', 'straße'],
  ['wussten', 'wussten'], // unchanged
  ['Russland', 'Russland'], // unchanged
];

const files = [
  'src/lib/content/spurig-voice.ts',
  'src/lib/content/ideas.ts',
  'src/lib/content/repurpose.ts',
];

for (const f of files) {
  let text = readFileSync(f, 'utf8');
  let changes = 0;
  for (const [from, to] of replacements) {
    if (from === to) continue;
    const before = text.split(from).length - 1;
    if (before > 0) {
      text = text.split(from).join(to);
      changes += before;
    }
  }
  writeFileSync(f, text, 'utf8');
  console.log(`${f}: ${changes} replacements`);
}
